version: '2'

services:
    application:
        container_name: gmt_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: gmt_workspace
        restart: always
        image: kenini1805/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: gmt_php-fpm
        restart: always
        image: kenini1805/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: gmt_nginx
        restart: always
        image: framgia/laravel-nginx
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "80:80"
        links:
            - php-fpm
    data:
        container_name: gmt_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    data_test:
        container_name: gmt_data_test
        image: debian
        volumes:
            - .docker/mysql_test:/var/lib/mysql
            - .docker/data_test:/data
    logs:
        container_name: gmt_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/mongodb:/var/log/mongodb
    mysql:
        container_name: gmt_mysql
        restart: always
        image: mysql:5.7
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: gmt
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
            